wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1666877641.68628
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
lr:
  desc: null
  value: 0.001
