name: myenv
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyh4f3eec9_6
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1o=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - python=3.6.8=h0371630_0
  - pytorch=1.10.2=py3.6_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.11.3=py36_cu113
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cycler==0.11.0
    - decorator==4.4.2
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - gensim==3.8.1
    - gitdb==4.0.9
    - gitpython==3.1.18
    - idna==3.3
    - imageio==2.15.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - matplotlib==3.1.1
    - networkx==2.5.1
    - nltk==3.4.5
    - numba==0.53.1
    - numpy==1.19.5
    - packaging==21.3
    - pandas==0.25.3
    - pathtools==0.1.2
    - pillow==8.4.0
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.1
    - pydantic==1.9.1
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - pytorch-ignite==0.4.9
    - pytz==2022.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - requests==2.27.1
    - scikit-image==0.15.0
    - scikit-learn==0.24.2
    - scipy==1.3.2
    - seaborn==0.9.0
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - sklearn==0.0
    - smart-open==6.0.0
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - torchaudio==0.10.2+cu113
    - torchfile==0.1.0
    - torchnet==0.0.4
    - tornado==6.1
    - tqdm==4.64.0
    - umap-learn==0.1.1
    - urllib3==1.26.9
    - visdom==0.1.8.9
    - wandb==0.12.17
    - websocket-client==1.3.1
    - zipp==3.6.0
prefix: /home/agathe/Code/miniconda3/envs/myenv
