wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: loss_0_train
      5: 1
      6:
      - 1
    - 1: loss_1_train
      5: 1
      6:
      - 1
    - 1: loss_train
      5: 1
      6:
      - 1
    - 1: kld_prior_train
      5: 1
      6:
      - 1
    - 1: reg_train
      5: 1
      6:
      - 1
    - 1: beta_kl
      5: 1
      6:
      - 1
    python_version: 3.6.10
    start_time: 1664897827
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 7
      - 16
      4: 3.6.10
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 256
beta_kl:
  desc: null
  value: 1
beta_prior:
  desc: null
  value: 1.0
data_path:
  desc: null
  value: ../data/
decrease_beta_kl:
  desc: null
  value: 1
dist:
  desc: null
  value: normal
epochs:
  desc: null
  value: 30
experiment:
  desc: null
  value: contour
fix_decoders:
  desc: null
  value: true
fix_jencoder:
  desc: null
  value: true
freq_analytics:
  desc: null
  value: 5
latent_dim:
  desc: null
  value: 15
learn_prior:
  desc: null
  value: false
llik_scaling:
  desc: null
  value: 0.0
logp:
  desc: null
  value: false
looser:
  desc: null
  value: false
loss:
  desc: null
  value: mse
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: jnf_mnist_contour
no_analytics:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
no_nf:
  desc: null
  value: false
no_recon:
  desc: null
  value: false
num_hidden_layers:
  desc: null
  value: 1
obj:
  desc: null
  value: jmvae_nf
print_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
skip_warmup:
  desc: null
  value: false
use_pretrain:
  desc: null
  value: ''
warmup:
  desc: null
  value: 15
