name: myenv38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.14.6=py38ha65f79e_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=37.0.2=py38h2b5fc30_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - pip=22.2.2=py38h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu116
  - torchvision=0.13.1=py38_cu116
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - beautifulsoup4==4.11.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - dataclasses==0.6
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - filelock==3.8.0
    - fonttools==4.37.4
    - gdown==4.5.1
    - gitdb==4.0.9
    - gitpython==3.1.29
    - imageio==2.22.1
    - importlib-metadata==5.0.0
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - matplotlib==3.6.1
    - networkx==2.8.7
    - nltk==3.7
    - numba==0.56.2
    - numpy==1.23.3
    - packaging==21.3
    - pandas==1.5.0
    - pathtools==0.1.2
    - pickle5==0.0.11
    - pillow==9.2.0
    - promise==2.3
    - protobuf==4.21.7
    - psutil==5.9.2
    - pydantic==1.10.2
    - pynndescent==0.5.7
    - pyparsing==3.0.9
    - pythae==0.0.8
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.9.13
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.2
    - seaborn==0.12.0
    - sentry-sdk==1.9.10
    - setproctitle==1.3.2
    - setuptools==59.8.0
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - torch==1.12.1
    - torchnet==0.0.4
    - tornado==6.2
    - tqdm==4.64.1
    - umap-learn==0.5.3
    - visdom==0.2.1
    - wandb==0.13.4
    - websocket-client==1.4.1
    - zipp==3.9.0
prefix: /home/agathe/Code/miniconda3/envs/myenv38
